"""update all db tables

Revision ID: bb8f8d69c05a
Revises: 91ff5dbb49f9
Create Date: 2026-03-04 15:17:48.710527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb8f8d69c05a'
down_revision: Union[str, Sequence[str], None] = '91ff5dbb49f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('product', sa.Column('category_id', sa.Integer(), nullable=True))
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('product', 'price',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'product', 'category', ['category_id'], ['id'])
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.alter_column('product', 'price',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('product', 'category_id')
    op.alter_column('category', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
